
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://stately-sunburst-dbafe0.netlify.app/" # the base hostname & protocol for your site, e.g. http://example.com

#######################################################################
# Settings related to the Header and your About page go here,such as 
# your name, site name, profile pic, site tagline, your bio, 
# your social media links etc
#######################################################################

heading: JARDIM DIGITAL W4LKER
subheading: # subheading won't work without a tagline, 
          # tagline is mandatory if you want the 
          # suheading to appear. The reason is
          # having a heading and a subheading looks 
          # ridiculous.
  enabled: true
  name: W4LKER
tagline: # subheading won't work without a tagline, 
         # tagline is mandatory if you want the 
         # suheading to appear. The reason is
         # having a heading and a subheading looks 
         # ridiculous.
         # Although you can have the tagline without 
         # the subheading to support the main heading
         # which in this case is 'Knowledge Continuum'
  enabled: true
  name: NOTAS E IDEIAS
copyright: 
  year: 2023
  msg: w4lker # This is a mandatory attribute for copyright to be displayed

user:
  display: false # setting it to false will remove the header image and bio
                # Note that user settings come wholesale, it does not have the 
                # granular enabling or disabling as with the 'preferences'
                # or the site-wide settings.
  name: Raghuveer S
  bio: Programmer Writer. Interested in constraints and correspondences.
  email: raghu-veer@outlook.com
  photo: /assets/img/profile.png
  alt_link: rgvr.me
  social: # just leave the field blank or type in null, if you don't have a
          # particular social media account and it won't appear
    enabled: false  # turn this to true
    twitter: rgvrme
    github: rgvr 
    youtube: rgvr 
    linkedin: rgvr  
    twitch: null
    facebook: null 
    instagram: null



#####################################################################
# Settings related to your preferences go here, such as the
# search results, wiki-style-links, sidenotes, marginnotes, 
# transclusion, pagepreview, backlinks, related posts, highlighting, 
# context menu, flashcards, sliding window, wrapping
#####################################################################
preferences:
  search:
    enabled: true
    shortcut_hint: 
        enabled: false
  wiki_style_link: # This property handles wiki style links '[['
    enabled: true
  sidenotes: 
    enabled: true
  transclusion:
    enabled: true
  image:
    enabled: true
  pagepreview:
    enabled: true
  highlighting:
    enabled: true
    color: 004e82 # Takes hexadecimal and basic names like white, red, etc. 
                  # Do not add '#'(the pound symbol) before the hexadecimal number.
                  # In yml, it is considered as a comment
  backlinks:
    enabled: true
  related:
    enabled: true # This enables the posts that are related to each other by tags
  wrapping:
    enabled: true
  contextmenu:
    enabled: true
    copylink: 
      enabled: true
    newtab: 
      enabled: true
    backlinks: 
      enabled: true
    related: 
      enabled: true
  flashcards:
    enabled: true

encoding: utf-8

# Build settings
theme: null
plugins:
  - jekyll-feed 
  - jekyll-sitemap 
  - jekyll-tidy

 
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: katex
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  
sass:
  style: compressed

collections:
  posts:
    output: true
    permalink: /:categories/:title
    name: Meus posts
    filename_pattern: posts-:title
    


defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: Post
      permalink: /:categories/:title:output_ext
      content-type: post
      show_drafts: true



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
